stages:
  - tests
  - build
  - deploy

.test:
  image: rnds/ruby:2.5-test
  stage: tests
  variables:
    COMPOSE_PROJECT_NAME: timeouter_${CI_PIPELINE_ID}_${CI_JOB_ID}
  script:
    - bundle install --jobs=3 --path vendor/bundle && bundle package --all
    - docker-compose build --force-rm --pull test-${CASE}
    - docker-compose up --force-recreate -t 1 --remove-orphans -d test-${CASE}
    - docker-compose exec -T test-${CASE} rspec
    - docker-compose exec -T test-${CASE} cat rspec.xml > rspec-${CASE}.xml
    - ls -al
    - cat rspec*
  after_script:
    - docker-compose down -v --remove-orphans
  artifacts:
    reports:
      junit: rspec*.xml

test-2.5:
  extends: .test
  variables:
    CASE: 2.5

test-2.6:
  extends: .test
  variables:
    CASE: 2.6


# build:
#   image: rnds/ruby:2.5-test
#   stage: build
#   variables:
#     BUILDVERSION: ${CI_PIPELINE_ID}
#   script:
#     - bundle install --jobs=3 --path vendor/bundle && bundle package --all
#     - gem build `ls | grep gemspec` && gem install `ls | grep -e '.gem$'` 
#   cache:
#     paths:
#       - vendor/bundle
#       - vendor/cache
#   artifacts:
#     name: "gem"
#     paths:
#       - ./*.gem

# pushgem:
#   image: rnds/ruby:2.5-test
#   stage: deploy
#   script:
#     - mkdir -p ~/.gem
#     - 'echo ":rubygems_api_key: ${RUBYGEMS_KEY}" > ~/.gem/credentials'
#     - chmod 600 ~/.gem/credentials
#     - export GEMFILE=`ls *.gem | tail -n 1`
#     - gem push $GEMFILE
#   only:
#     - master

# deps:
#   image: rnds/ruby:2.5-test
#   stage: deploy
#   cache: {}
#   allow_failure: true
#   script:
#     - bundle audit update
#     - bundle audit || true
#     - bundle outdated --only-explicit --no-pre --group default || true
#     - vulnerable=$(bundle audit | grep "Name:" | sort | uniq | wc -l) || true
#     - outdated=$(bundle outdated --only-explicit --no-pre --group default | grep "*" | wc -l) || true
#     - curl "https://badgen.net/badge/vulnerable%20gems/${vulnerable}/red" > vulnerable.svg
#     - curl "https://badgen.net/badge/outdated%20gems/${outdated}/orange" > outdated.svg
#     - curl -L -X PUT --header "PRIVATE-TOKEN:$BOT_TOKEN" --form "title=Vulnerable gems badge" --form "file_name=vulnerable.svg" --form "code=<vulnerable.svg" --form "description=Vulnerable dependency gems" https://br.rnds.pro/api/v4/projects/$CI_PROJECT_ID/snippets/42
#     - curl -L -X PUT --header "PRIVATE-TOKEN:$BOT_TOKEN" --form "title=Outdaged gems badge" --form "file_name=outdated.svg" --form "code=<outdated.svg" --form "description=Outdated direct dependency gems" https://br.rnds.pro/api/v4/projects/$CI_PROJECT_ID/snippets/43
#   only: 
#     - master
